server:
  port: ${SERVER_PORT:8083}
spring:
  application:
    name: mysql-mcp-server
  main:
    banner-mode: off
    #web-application-type: none
    web-application-type: SERVLET
  # 数据库配置
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:ledger}?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=${MYSQL_SERVER_TIMEZONE:Asia/Shanghai}&allowPublicKeyRetrieval=true}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:oneapimmysql}
    database: ${SPRING_DATASOURCE_DATABASE:${MYSQL_DATABASE:ledger}}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 300000
      connection-timeout: 20000
      connection-test-query: SELECT 1
      pool-name: mcp-server-pool
      max-lifetime: 1800000
      validation-timeout: 5000
      connection-init-sql: SET NAMES utf8mb4;


  # MCP 配置
  ai:
    mcp:
      server:
        enabled: true
        name: mysql_mcp_server
        version: 1.0.0
        sse-endpoint: /api/v1/sse
        sse-message-endpoint: /api/v1/mcp
        capabilitites:
          tool: true
config:
  database:
    read-only-tables: ${CONFIG_DATABASE_READ_ONLY_TABLES:ctg_ledger_annual_budget,ctg_ledger_project,ctg_ledger_project_expense_detail,ctg_ledger_project_user,sys_user,sys_dept}
    read-rows-limit: ${CONFIG_DATABASE_READ_ROWS_LIMIT:200}

# 日志配置
logging:
  level:
    root: INFO
    com.zcckj.mcpserver: DEBUG
    org.springframework: INFO
    org.springframework.boot.context.config: DEBUG
    org.springframework.core.env: DEBUG

  file:
    name: ${LOG_FILE_NAME:logs/mcp-server.log}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"
